include: package:flutter_lints/flutter.yaml

linter:
  rules:
     avoid_print: true
     prefer_single_quotes: true
     avoid_function_literals_in_foreach_calls: false
     always_declare_return_types: false
     curly_braces_in_flow_control_structures: false